[project]
name = "opportunities-details"
version = "0.5.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "aiohttp>=3.13.2",
    "bs4>=0.0.2",
    "faiss-cpu>=1.12.0",
    "fastapi>=0.128.0",
    "flashrank>=0.2.10",
    "gemma>=3.2.1",
    "icecream>=2.1.8",
    "langchain>=1.0.7",
    "langchain-community>=0.4.1",
    "langchain-huggingface>=1.0.1",
    "langchain-ollama>=1.0.0",
    "lxml>=6.0.2",
    "ollama>=0.6.1",
    "python-slugify>=8.0.4",
    "rapidfuzz>=3.14.3",
    "readability-lxml>=0.8.4.1",
    "requests>=2.32.5",
    "sentence-transformers>=5.1.2",
    "streamlit>=1.51.0",
    "tiktoken>=0.12.0",
    "torch",
    "trafilatura>=2.0.0",
    "transformers>=4.57.1",
    "uvicorn>=0.40.0",
]

[dependency-groups]
dev = [
    "uv-bump>=0.2.0",
]

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch" }]
torchvision = [{ index = "pytorch" }]
torchaudio = [{ index = "pytorch" }]

